#!/usr/bin/env bash
#while loop that utilizes cases and prints some string
n=1
while [[ $n -le 20 ]]
do
case $n in
	4) echo -e "$n\nbad luck from China" ;;
	9) echo -e "$n\nbad luck from Japan" ;;
	17) echo -e "$n\nbad luck from Italy" ;;
	*) echo "$n" ;;
esac
(( n++ ))
done
