#!/usr/bin/env bash
#display of hours and minutes
hr=0


while [ "$hr" -le 12 ]; do
printf "Hour: %d\n" "$hr"


	min=1
	while [ "$min" -le 59 ]; do
		printf "%d\n" "$min"
		(( min++ ))
	done


	(( hr++ ))	
done
